package:
  name: "routoolpa"
  version: "0.114"
about:
  summary: "Routines, Tools and Parsers"
source:
  path: ../
requirements:
  build:
    - python {{ python }}
    - pip
    - setuptools
    - ete3
    - scipy
    - "numpy>=1.26"
    - pandas
    - matplotlib
    - statsmodels
    - biopython
    - pyparsing
    - xmltodict
    - venn
    - bcbio-gff
  run:
    - python
    - scipy
    - "numpy>=1.26"
    - pandas
    - matplotlib
    - ete3
    - statsmodels
    - pyparsing
    - xmltodict
    - biopython
    - venn
    - bcbio-gff
    - xlsxwriter

build:
  script: python setup.py install